import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

const myFontRegular = localFont({
	src: '/fonts/BeVietnamPro-Regular.ttf',
	weight: '400',
	variable: '--font-myFont-regular',
});

export const metadata: Metadata = {
	title: 'STDEV AI Course Generator',
	description: 'Generated by STDEV',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`${myFontRegular} antialiased`}>{children}</body>
			</html>
		</ClerkProvider>
	);
}
